### PR TITLE
Fix issues #4

### PR DESCRIPTION
**Pull request by giautm**

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Hmm, I installed the latest version of `create-react-native-app` and created a blank project. When bundling I get this error:

```
 INFO  Haul is now bundling your React Native app in production mode.

Starting from:
iOS        [====================] 100%
/Users/hein/repos/scratch/bundle-visualizer-test/node_modules/react-native-scripts/build/bin/crna-entry.js

 ERROR  Failed to compile.

./node_modules/@expo/vector-icons/fonts/FontAwesome.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
@ ./node_modules/@expo/vector-icons/FontAwesome.js 1:466-500
@ ./node_modules/@expo/vector-icons/index.js
@ ./node_modules/expo/src/Icon.js
@ ./node_modules/expo/src/Expo.js
@ ./node_modules/react-native-scripts/build/bin/crna-entry.js
@ multi ./node_modules/haul/src/utils/polyfillEnvironment.js ./node_modules/react-native-scripts/build/bin/crna-entry.js
...
```

**Comment by IjzerenHein** [comment]
I also upgraded the latest version of haul. Seems to be a problem in beta 13 which was fixed here.
https://github.com/callstack/haul/issues/347

I'm gonna wait a couple days to see whether this gets released, and otherwise revert back to the old version of Haul.

**Comment by IjzerenHein** [comment]
O hell, just realised that you are the one who fixed the haul issue, lol 😃 👍 🤘

**Comment by giautm** [comment]
Yeah, I wait for that release too. :D I want to use the original version of `react-native-bundle-visualizer` instead of my fork. :D

**Pull request merged**
